pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }
        stage('create/activate venv') {
            steps {
                sh '''
                cd mysite
                virtualenv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('setup db') {
            steps {
                sh '''
                python manage.py makemigrations
                python manage.py migrate
                '''
            }
        }
        stage('populate db') {
            steps {
                 sh 'python manage.py seed polls'
            }

        }

        stage('Test') {
            steps {
                sh 'python manage.py test polls'
        }
    }
}
}
